name: 43
timestamp: 1555874089
version: 7
preset:
  image: 'gantry-admin://images/layouts/body-only.png'
  name: _body_only
  timestamp: 1481092873
positions: {  }
sections:
  mainbar: Mainbar
particles:
  custom:
    custom-8951: 'Custom HTML'
  content:
    system-content-5845: 'Page Content'
  messages:
    system-messages-6659: 'System Messages'
inherit: {  }
