version: 2
preset:
  image: 'gantry-admin://images/layouts/body-only.png'
  name: _body_only
  timestamp: 1481092873
layout:
  /mainbar/:
    -
      - custom-8951
    -
      - system-content-5845
    -
      - system-messages-6659
structure:
  mainbar:
    type: section
    subtype: main
    attributes:
      boxed: ''
      class: ''
      variations: ''
content:
  custom-8951:
    title: 'Custom HTML'
    attributes:
      html: "<embed src=\"https://service.mercedes-benz.ru/?dealer=service.mercedes-panavto.ru\" width=\"1200\"\n       height=\"600\">"
