name: _error
timestamp: 1533062597
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: _error
  timestamp: 1533062597
positions:
  footer: Footer
sections:
  header: Header
  navigation: Navigation
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-2926: Logo
  spacer:
    spacer-7734: Spacer
    spacer-4104: Spacer
  menu:
    menu-1587: Menu
  content:
    system-content-3785: 'Page Content'
  position:
    position-footer: Footer
  copyright:
    copyright-1905: Copyright
  branding:
    branding-9928: Branding
  mobile-menu:
    mobile-menu-4333: Mobile-menu
inherit: {  }
