version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: _error
  timestamp: 1533062597
layout:
  /header/:
    -
      - 'logo-2926 30'
      - 'spacer-7734 70'
  /navigation/:
    -
      - menu-1587
  /main/:
    -
      - system-content-3785
  /footer/:
    -
      - position-footer
    -
      - 'copyright-1905 40'
      - 'spacer-4104 30'
      - 'branding-9928 30'
  offcanvas:
    -
      - mobile-menu-4333
structure:
  header:
    attributes:
      boxed: ''
  navigation:
    type: section
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  position-footer:
    attributes:
      key: footer
