atoms:
  -
    id: fixed-header-3960
    type: fixed-header
    title: 'Fixed Header'
    inherit:
      outline: default
      atom: fixed-header-3960
      include:
        - attributes
  -
    id: uikit-1560
    type: uikit
    title: 'UIkit for Gantry5'
    inherit:
      outline: default
      atom: uikit-1560
      include:
        - attributes
  -
    id: headroom-8368
    type: headroom
    title: Headroom.js
    inherit:
      outline: default
      atom: headroom-8368
      include:
        - attributes
  -
    id: analytics-5408
    type: analytics
    title: 'Google Analytics'
    inherit:
      outline: default
      atom: analytics-5408
      include:
        - attributes
  -
    title: 'Back To Top'
    type: backtotop
    id: backtotop-8597
    inherit:
      outline: default
      atom: backtotop-8597
      include:
        - attributes
  -
    title: 'Cookie Consent'
    type: cookie-consent
    id: cookie-consent-6997
    inherit:
      outline: default
      atom: cookie-consent-6997
      include:
        - attributes
