name: '13'
timestamp: 1475656803
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1475608600
positions:
  mainbar: Mainbar
  sidebar: Sidebar
sections:
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  header: Header
  mainbar: Mainbar
  sidebar: Sidebar
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-2234: 'Logo / Image'
    logo-9901: 'Logo / Image'
  menu:
    menu-4005: Menu
  social:
    social-4145: Social
  content:
    system-content-5435: 'Page Content'
  position:
    position-position-5639: Mainbar
    position-position-6305: Sidebar
  copyright:
    copyright-2945: Copyright
  horizontalmenu:
    horizontalmenu-9198: 'Horizontal Menu'
  totop:
    totop-7113: 'To Top'
  mobile-menu:
    mobile-menu-3033: Mobile-menu
inherit:
  default:
    navigation: navigation
    logo-2234: logo-9608
    menu-4005: menu-6409
    social-4145: social-3171
    header: header
    intro: intro
    features: features
    utility: utility
    above: above
    testimonials: testimonials
    expanded: expanded
    mainbar: mainbar
    system-content-5435: system-content-1587
    sidebar: sidebar
    position-position-6305: position-position-3949
    footer: footer
    logo-9901: logo-9571
    copyright-2945: copyright-1736
    horizontalmenu-9198: horizontalmenu-9034
    totop-7113: totop-8670
    offcanvas: offcanvas
    mobile-menu-3033: mobile-menu-5697
