version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1475608600
layout:
  navigation: {  }
  header: {  }
  intro: {  }
  features: {  }
  utility: {  }
  above: {  }
  testimonials: {  }
  expanded: {  }
  /container-main/:
    -
      -
        'mainbar 75':
          -
            - system-content-5435
          -
            - position-position-5639
      -
        'sidebar 25': {  }
  footer: {  }
  offcanvas: {  }
structure:
  navigation:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  header:
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  intro:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  features:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  utility:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  above:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  testimonials:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  expanded:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  mainbar:
    type: section
    subtype: main
    inherit:
      outline: default
      include:
        - attributes
        - block
  sidebar:
    type: section
    subtype: aside
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  container-main:
    attributes:
      boxed: ''
  footer:
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  offcanvas:
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
content:
  system-content-5435:
    inherit:
      outline: default
      include:
        - attributes
        - block
      particle: system-content-1587
  position-position-5639:
    title: Mainbar
    attributes:
      key: mainbar
