name: 15
timestamp: 1475656374
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1468340932
positions:
  sidebar: Sidebar
sections:
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  header: Header
  mainbar: Mainbar
  sidebar: Sidebar
  footer: Footer
  offcanvas: Offcanvas
particles:
  custom:
    custom-9029: Header
    custom-7890: Content
  logo:
    logo-2145: 'Logo / Image'
    logo-2746: 'Logo / Image'
  menu:
    menu-1836: Menu
  social:
    social-5014: Social
  position:
    position-position-3929: Sidebar
  copyright:
    copyright-3744: Copyright
  horizontalmenu:
    horizontalmenu-2731: 'Horizontal Menu'
  totop:
    totop-4310: 'To Top'
  mobile-menu:
    mobile-menu-7046: Mobile-menu
inherit:
  default:
    navigation: navigation
    sidebar: sidebar
    footer: footer
    offcanvas: offcanvas
    logo-2145: logo-9608
    menu-1836: menu-6409
    social-5014: social-3171
    position-position-3929: position-position-3949
    logo-2746: logo-9571
    copyright-3744: copyright-1736
    horizontalmenu-2731: horizontalmenu-9034
    totop-4310: totop-8670
    mobile-menu-7046: mobile-menu-5697
