name: 20
timestamp: 1475656577
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1468340932
positions: {  }
sections:
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  header: Header
  mainbar: Mainbar
  aside: Aside
  sidebar: Sidebar
  footer: Footer
  offcanvas: Offcanvas
particles:
  custom:
    custom-6833: Header
    custom-5490: Content
    custom-6361: 'Right Sidebar'
    custom-4736: Lipsum
    custom-9374: 'Flexible Layouts'
    custom-4266: Lipsum
  logo:
    logo-5520: 'Logo / Image'
    logo-4140: 'Logo / Image'
  menu:
    menu-1364: Menu
  social:
    social-7580: Social
  copyright:
    copyright-3939: Copyright
  horizontalmenu:
    horizontalmenu-6591: 'Horizontal Menu'
  totop:
    totop-8898: 'To Top'
  mobile-menu:
    mobile-menu-9581: Mobile-menu
inherit:
  default:
    navigation: navigation
    footer: footer
    offcanvas: offcanvas
    logo-5520: logo-9608
    menu-1364: menu-6409
    social-7580: social-3171
    logo-4140: logo-9571
    copyright-3939: copyright-1736
    horizontalmenu-6591: horizontalmenu-9034
    totop-8898: totop-8670
    mobile-menu-9581: mobile-menu-5697
