tinyMCE.addI18n('ru.advanced',{
    style_select:"Стили",
    font_size:"Размер шрифта",
    fontdefault:"Шрифт",
    block:"Формат",
    paragraph:"Абзац",
    div:"Div",
    address:"Адрес",
    pre:"Заданный формат",
    h1:"Заголовок 1",
    h2:"Заголовок 2",
    h3:"Заголовок 3",
    h4:"Заголовок 4",
    h5:"Заголовок 5",
    h6:"Заголовок 6",
    blockquote:"Цитата",
    code:"Код",
    samp:"Пример кода",
    dt:"Термин",
    dd:"Описание",
    span:"Интервал",
    section:"Раздел",
    article:"Статья",
    hgroup:"Группа заголовков",
    aside:"Блок",
    figure:"Группа элементов",
    bold_desc:"Полужирный (Ctrl+B)",
    italic_desc:"Курсив (Ctrl+I)",
    underline_desc:"Подчеркнутый (Ctrl+U)",
    striketrough_desc:"Зачеркнутый",
    justifyleft_desc:"По левому краю",
    justifycenter_desc:"По центру",
    justifyright_desc:"По правому краю",
    justifyfull_desc:"По ширине",
    bullist_desc:"Маркированный список",
    numlist_desc:"Нумерованный список",
    outdent_desc:"Уменьшить отступ",
    indent_desc:"Увеличить отступ",
    undo_desc:"Отменить (Ctrl+Z)",
    redo_desc:"Повторить (Ctrl+Y)",
    link_desc:"Добавить/Изменить ссылку",
    unlink_desc:"Удалить ссылку",
    image_desc:"Добавить/Изменить изображение",
    cleanup_desc:"Очистить HTML-код",
    code_desc:"Редактировать HTML-код",
    sub_desc:"Подстрочный знак",
    sup_desc:"Надстрочный знак",
    hr_desc:"Горизонтальная линия",
    removeformat_desc:"Очистить формат",
    custom1_desc:"Пользовательское описание",
    forecolor_desc:"Цвет текста",
    backcolor_desc:"Цвет фона",
    charmap_desc:"Символ",
    visualaid_desc:"Показать/скрыть невидимые элементы",
    cut_desc:"Вырезать",
    copy_desc:"Копировать",
    paste_desc:"Вставить",
    image_props_desc:"Параметры изображения",
    newdocument_desc:"Новый документ",
    help_desc:"Помощь",
    blockquote_desc:"Цитата",
    clipboard_msg:"Функция Копировать/Вырезать/Вставить не доступна в Mozilla и Firefox.\r\nВы хотите узнать подробнее об этой ошибке?",
    path:"Теги",
    newdocument:"Вы действительно хотите удалить всё содержимое?",
    toolbar_focus:"Перейти к кнопкам инструментов - Alt+Q, перейти к редактору - Alt-Z, перейти к пути элемента - Alt-X",
    more_colors:"Другие цвета",
	
    // Accessibility Strings
    shortcuts_desc:'Доступность',
    help_shortcut:'. Нажмите ALT F10 для панели инструментов. Нажмите ALT 0 для помощи.',
    rich_text_area:"Визуальный редактор",
    toolbar:"Панель инструментов"
});