name: '27'
timestamp: 1481293834
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: _error
  timestamp: 1468340932
positions: {  }
sections:
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  header: Header
  mainbar: Mainbar
  sidebar: Sidebar
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-4683: 'Logo / Image'
    logo-2829: 'Logo / Image'
  menu:
    menu-4016: Menu
  social:
    social-6357: Social
  custom:
    custom-8642: 'Custom HTML'
  content:
    system-content-1587: 'Page Content'
  copyright:
    copyright-9847: Copyright
  horizontalmenu:
    horizontalmenu-5451: 'Horizontal Menu'
  totop:
    totop-3073: 'To Top'
  mobile-menu:
    mobile-menu-2850: Mobile-menu
inherit:
  default:
    navigation: navigation
    logo-4683: logo-9608
    menu-4016: menu-6409
    social-6357: social-3171
    footer: footer
    logo-2829: logo-9571
    copyright-9847: copyright-1736
    horizontalmenu-5451: horizontalmenu-9034
    totop-3073: totop-8670
    offcanvas: offcanvas
    mobile-menu-2850: mobile-menu-5697
