name: 35
timestamp: 1555874079
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1505850393
positions:
  aside: Aside
  sidebar: Sidebar
sections:
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  header: Header
  aside: Aside
  sidebar: Sidebar
  mainbar: Mainbar
  footer: Footer
  offcanvas: Offcanvas
particles:
  owlcarousel:
    owlcarousel-6883: 'Owl Carousel'
  content-pro-joomla:
    content-pro-joomla-6821: 'Content PRO (Joomla)'
  position:
    position-position-6169: Aside
    position-position-8085: Sidebar
  module:
    position-module-7069: 'Module Instance'
    position-module-5081: 'Login-top Module'
    position-module-2726: 'Module Instance'
    position-module-1901: 'Module Instance'
  top-news-joomla:
    top-news-joomla-4393: 'Top News (Joomla)'
  contentarray:
    contentarray-5898: 'Joomla Articles'
  spacer:
    spacer-2818: Spacer
    spacer-4685: Spacer
    spacer-4612: Spacer
    spacer-3076: Spacer
    spacer-5880: Spacer
    spacer-9569: Spacer
    spacer-9332: Spacer
  logo:
    logo-1443: 'Logo / Image'
    logo-4997: 'Logo / Image'
  menu:
    menu-7978: Menu
  paypaldonate:
    paypaldonate-5428: 'Paypal Donate'
  social:
    social-8906: Social
  mobile-menu:
    mobile-menu-7707: Mobile-menu
inherit:
  default:
    navigation: navigation
    intro: intro
    testimonials: testimonials
    expanded: expanded
    position-position-6169: position-position-4734
    position-position-8085: position-position-3949
    footer: footer
    offcanvas: offcanvas
    spacer-2818: spacer-2975
    position-module-5081: position-module-6976
    spacer-4685: spacer-8255
    position-module-2726: position-module-4966
    spacer-4612: spacer-6813
    spacer-3076: spacer-5480
    logo-1443: logo-3321
    spacer-5880: spacer-8967
    menu-7978: menu-1386
    spacer-9569: spacer-4109
    logo-4997: logo-9571
    paypaldonate-5428: paypaldonate-7867
    spacer-9332: spacer-4934
    social-8906: social-6571
    position-module-1901: position-module-2100
    mobile-menu-7707: mobile-menu-5697
