name: 21
timestamp: 1555874076
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1505850393
positions: {  }
sections:
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  header: Header
  aside: Aside
  sidebar: Sidebar
  mainbar: Mainbar
  footer: Footer
  offcanvas: Offcanvas
particles:
  spacer:
    spacer-4452: Spacer
    spacer-8382: Spacer
    spacer-5480: Spacer
    spacer-4109: Spacer
    spacer-5248: Spacer
    spacer-7190: Spacer
    spacer-8890: Spacer
    spacer-3327: Spacer
  module:
    position-module-1240: 'Module Instance'
    position-module-6312: 'Module Instance'
    position-module-3545: 'Module Instance'
    position-module-6986: 'Module Instance'
    position-module-9481: 'Login-top Module'
    position-module-7973: 'Module Instance'
    position-module-7677: 'Module Instance'
  menu:
    menu-1386: Menu
  content:
    system-content-7056: 'Page Content'
  logo:
    logo-8318: 'Logo / Image'
  paypaldonate:
    paypaldonate-7557: 'Paypal Donate'
  social:
    social-7393: Social
  mobile-menu:
    mobile-menu-9881: Mobile-menu
inherit:
  default:
    navigation: navigation
    utility: utility
    above: above
    testimonials: testimonials
    expanded: expanded
    footer: footer
    offcanvas: offcanvas
    spacer-5248: spacer-2975
    position-module-9481: position-module-6976
    spacer-7190: spacer-8255
    position-module-7973: position-module-4966
    spacer-8890: spacer-6813
    logo-8318: logo-9571
    paypaldonate-7557: paypaldonate-7867
    spacer-3327: spacer-4934
    social-7393: social-6571
    position-module-7677: position-module-2100
    mobile-menu-9881: mobile-menu-5697
