name: 17
timestamp: 1475656541
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1468340932
positions: {  }
sections:
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  header: Header
  mainbar: Mainbar
  sidebar: Sidebar
  footer: Footer
  offcanvas: Offcanvas
particles:
  custom:
    custom-6833: Header
    custom-5490: Content
    custom-6361: 'Right Sidebar'
    custom-9374: 'Flexible Layouts'
  logo:
    logo-6193: 'Logo / Image'
    logo-2414: 'Logo / Image'
  menu:
    menu-3584: Menu
  social:
    social-4889: Social
  copyright:
    copyright-3813: Copyright
  horizontalmenu:
    horizontalmenu-1728: 'Horizontal Menu'
  totop:
    totop-2072: 'To Top'
  mobile-menu:
    mobile-menu-6725: Mobile-menu
inherit:
  default:
    navigation: navigation
    footer: footer
    offcanvas: offcanvas
    logo-6193: logo-9608
    menu-3584: menu-6409
    social-4889: social-3171
    logo-2414: logo-9571
    copyright-3813: copyright-1736
    horizontalmenu-1728: horizontalmenu-9034
    totop-2072: totop-8670
    mobile-menu-6725: mobile-menu-5697
