name: 14
timestamp: 1475656057
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1468340932
positions:
  sidebar: Sidebar
sections:
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  header: Header
  mainbar: Mainbar
  sidebar: Sidebar
  footer: Footer
  offcanvas: Offcanvas
particles:
  content:
    system-content-1948: 'Page Content'
  custom:
    custom-4778: 'Box 1'
    custom-9665: 'Box 2'
    custom-2425: 'Box Outline'
    custom-4630: 'Box Gradient'
    custom-9906: 'Title 1'
    custom-5672: 'Title 2'
    custom-7940: 'Title Outline'
    custom-9630: 'Title Gradient'
    custom-3865: 'Box 1, Title 1'
    custom-1335: 'Box 2, Title 2'
    custom-2032: 'Box Outline, Title Outline'
    custom-1204: 'Box Gradient, Title Gradient'
    custom-9315: 'Mixed Variations'
    custom-6813: 'Box Gradient, Title 2'
    custom-7550: 'Box Outline, Title 1'
    custom-3068: 'Box Outline, Title Gradient'
    custom-4827: 'Box2, Title 1'
    custom-6016: 'Stylistic Variations'
    custom-2352: 'Box 1, Rounded'
    custom-7473: 'Box Outline, Shadow'
    custom-1717: 'Box 2, Disabled'
    custom-2883: 'Title Outline, Centered Title'
  logo:
    logo-3683: 'Logo / Image'
    logo-1318: 'Logo / Image'
  menu:
    menu-4694: Menu
  social:
    social-9194: Social
  position:
    position-position-3856: Sidebar
  copyright:
    copyright-4925: Copyright
  horizontalmenu:
    horizontalmenu-5269: 'Horizontal Menu'
  totop:
    totop-8805: 'To Top'
  mobile-menu:
    mobile-menu-7737: Mobile-menu
inherit:
  default:
    navigation: navigation
    header: header
    intro: intro
    features: features
    utility: utility
    above: above
    testimonials: testimonials
    expanded: expanded
    mainbar: mainbar
    system-content-1948: system-content-1587
    sidebar: sidebar
    footer: footer
    offcanvas: offcanvas
    logo-3683: logo-9608
    menu-4694: menu-6409
    social-9194: social-3171
    position-position-3856: position-position-3949
    logo-1318: logo-9571
    copyright-4925: copyright-1736
    horizontalmenu-5269: horizontalmenu-9034
    totop-8805: totop-8670
    mobile-menu-7737: mobile-menu-5697
