version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1468340932
layout:
  navigation: {  }
  header: {  }
  intro: {  }
  features: {  }
  utility: {  }
  above: {  }
  testimonials: {  }
  expanded: {  }
  /container-main/:
    -
      -
        'mainbar 75':
          -
            - system-content-1948
          -
            - 'custom-4778 25'
            - 'custom-9665 25'
            - 'custom-2425 25'
            - 'custom-4630 25'
          -
            - 'custom-9906 25'
            - 'custom-5672 25'
            - 'custom-7940 25'
            - 'custom-9630 25'
          -
            - 'custom-3865 25'
            - 'custom-1335 25'
            - 'custom-2032 25'
            - 'custom-1204 25'
          -
            - custom-9315
          -
            - 'custom-6813 50'
            - 'custom-7550 50'
          -
            - 'custom-3068 50'
            - 'custom-4827 50'
          -
            - custom-6016
          -
            - 'custom-2352 33.3'
            - 'custom-7473 33.3'
            - 'custom-1717 33.3'
          -
            - custom-2883
      -
        'sidebar 25': {  }
  footer: {  }
  offcanvas: {  }
structure:
  navigation:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  header:
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  intro:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  features:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  utility:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  above:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  testimonials:
    type: section
    inherit:
      outline: default
      include:
        - children
        - attributes
  expanded:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - children
  mainbar:
    type: section
    subtype: main
    inherit:
      outline: default
      include:
        - attributes
        - block
  sidebar:
    type: section
    subtype: aside
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  container-main:
    attributes:
      boxed: ''
  footer:
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  offcanvas:
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
content:
  system-content-1948:
    inherit:
      outline: default
      include:
        - attributes
        - block
      particle: system-content-1587
  custom-4778:
    title: 'Box 1'
    attributes:
      html: "<div class=\"g-title\">Box 1</div>\n<p>Phasellus molestie magna non est bibendum non venenatis nisl tempor. Suspendisse dictum feugiat nisl ut dapibus.</p>\n<a href=\"#\" class=\"button button-xsmall\">Button</a>"
    block:
      variations: box1
  custom-9665:
    title: 'Box 2'
    attributes:
      html: "<div class=\"g-title\">Box 2</div>\n<p>Phasellus molestie magna non est bibendum non venenatis nisl tempor. Suspendisse dictum feugiat nisl ut dapibus.</p>\n<a href=\"#\" class=\"button button-xsmall\">Button</a>"
    block:
      variations: box2
  custom-2425:
    title: 'Box Outline'
    attributes:
      html: "<div class=\"g-title\">Box Outline</div>\n<p>Phasellus molestie magna non est bibendum non venenatis nisl tempor. Suspendisse dictum feugiat nisl ut dapibus.</p>\n<a href=\"#\" class=\"button button-xsmall\">Button</a>"
    block:
      variations: box-outline
  custom-4630:
    title: 'Box Gradient'
    attributes:
      html: "<div class=\"g-title\">Box Gradient</div>\n<p>Phasellus molestie magna non est bibendum non venenatis nisl tempor. Suspendisse dictum feugiat nisl ut dapibus.</p>\n<a href=\"#\" class=\"button button-xsmall\">Button</a>"
    block:
      variations: box-gradient
  custom-9906:
    title: 'Title 1'
    attributes:
      html: "<div class=\"g-title\">Title 1</div>\n<p>Phasellus molestie magna non est bibendum non venenatis nisl tempor. Suspendisse dictum feugiat nisl ut dapibus.</p>\n<a href=\"#\" class=\"button button-xsmall\">Button</a>"
    block:
      variations: title1
  custom-5672:
    title: 'Title 2'
    attributes:
      html: "<div class=\"g-title\">Title 2</div>\n<p>Phasellus molestie magna non est bibendum non venenatis nisl tempor. Suspendisse dictum feugiat nisl ut dapibus.</p>\n<a href=\"#\" class=\"button button-xsmall\">Button</a>"
    block:
      variations: title2
  custom-7940:
    title: 'Title Outline'
    attributes:
      html: "<div class=\"g-title\">Title Outline</div>\n<p>Phasellus molestie magna non est bibendum non venenatis nisl tempor. Suspendisse dictum feugiat nisl ut dapibus.</p>\n<a href=\"#\" class=\"button button-xsmall\">Button</a>"
    block:
      variations: title-outline
  custom-9630:
    title: 'Title Gradient'
    attributes:
      html: "<div class=\"g-title\">Title Gradient</div>\n<p>Phasellus molestie magna non est bibendum non venenatis nisl tempor. Suspendisse dictum feugiat nisl ut dapibus.</p>\n<a href=\"#\" class=\"button button-xsmall\">Button</a>"
    block:
      variations: title-gradient
  custom-3865:
    title: 'Box 1, Title 1'
    attributes:
      html: "<div class=\"g-title\">Box 1, Title 1</div>\n<p>Phasellus molestie magna non est bibendum non venenatis nisl tempor. Suspendisse dictum feugiat nisl ut dapibus.</p>\n<a href=\"#\" class=\"button button-xsmall\">Button</a>"
    block:
      variations: 'box1 title1'
  custom-1335:
    title: 'Box 2, Title 2'
    attributes:
      html: "<div class=\"g-title\">Box 2, Title 2</div>\n<p>Phasellus molestie magna non est bibendum non venenatis nisl tempor. Suspendisse dictum feugiat nisl ut dapibus.</p>\n<a href=\"#\" class=\"button button-xsmall\">Button</a>"
    block:
      variations: 'box2 title2'
  custom-2032:
    title: 'Box Outline, Title Outline'
    attributes:
      html: "<div class=\"g-title\">Box Outline, Title Outline</div>\n<p>Phasellus molestie magna non est bibendum non venenatis nisl tempor. Suspendisse dictum feugiat nisl ut dapibus.</p>\n<a href=\"#\" class=\"button button-xsmall\">Button</a>"
    block:
      variations: 'box-outline title-outline'
  custom-1204:
    title: 'Box Gradient, Title Gradient'
    attributes:
      html: "<div class=\"g-title\">Box Gradient, Title Gradient</div>\n<p>Phasellus molestie magna non est bibendum non venenatis nisl tempor. Suspendisse dictum feugiat nisl ut dapibus.</p>\n<a href=\"#\" class=\"button button-xsmall\">Button</a>"
    block:
      variations: 'box-gradient title-gradient'
  custom-9315:
    title: 'Mixed Variations'
    attributes:
      html: "<h2 class=\"g-title\">Mixed Variations</h2>\n<p>You can mix and combine different variations together to achieve interesting results.</p>"
  custom-6813:
    title: 'Box Gradient, Title 2'
    attributes:
      html: "<div class=\"g-title\">Box Gradient, Title 2</div>\n<p>Phasellus molestie magna non est bibendum non venenatis nisl tempor. Suspendisse dictum feugiat nisl ut dapibus.</p>\n<a href=\"#\" class=\"button button-xsmall\">Button</a>"
    block:
      variations: 'box-gradient title2'
  custom-7550:
    title: 'Box Outline, Title 1'
    attributes:
      html: "<div class=\"g-title\">Box Outline, Title 1</div>\n<p>Phasellus molestie magna non est bibendum non venenatis nisl tempor. Suspendisse dictum feugiat nisl ut dapibus.</p>\n<a href=\"#\" class=\"button button-xsmall\">Button</a>"
    block:
      variations: 'box-outline title1'
  custom-3068:
    title: 'Box Outline, Title Gradient'
    attributes:
      html: "<div class=\"g-title\">Box Outline, Title Gradient</div>\n<p>Phasellus molestie magna non est bibendum non venenatis nisl tempor. Suspendisse dictum feugiat nisl ut dapibus.</p>\n<a href=\"#\" class=\"button button-xsmall\">Button</a>"
    block:
      variations: 'box-outline title-gradient'
  custom-4827:
    title: 'Box2, Title 1'
    attributes:
      html: "<div class=\"g-title\">Box 2, Title 1</div>\n<p>Phasellus molestie magna non est bibendum non venenatis nisl tempor. Suspendisse dictum feugiat nisl ut dapibus.</p>\n<a href=\"#\" class=\"button button-xsmall\">Button</a>"
    block:
      variations: 'box2 title1'
  custom-6016:
    title: 'Stylistic Variations'
    attributes:
      html: '<h2 class="g-title">Stylistic Variations</h2>'
  custom-2352:
    title: 'Box 1, Rounded'
    attributes:
      html: "<div class=\"g-title\">Box 1, Rounded</div>\n<p>Phasellus molestie magna non est bibendum non venenatis nisl tempor. Suspendisse dictum feugiat nisl ut dapibus.</p>\n<a href=\"#\" class=\"button button-xsmall\">Button</a>"
    block:
      variations: 'box1 rounded'
  custom-7473:
    title: 'Box Outline, Shadow'
    attributes:
      html: "<div class=\"g-title\">Box Outline, Shadow</div>\n<p>Phasellus molestie magna non est bibendum non venenatis nisl tempor. Suspendisse dictum feugiat nisl ut dapibus.</p>\n<a href=\"#\" class=\"button button-xsmall\">Button</a>"
    block:
      variations: 'box-outline shadow'
  custom-1717:
    title: 'Box 2, Disabled'
    attributes:
      html: "<div class=\"g-title\">Box 2, Disabled</div>\n<p>Phasellus molestie magna non est bibendum non venenatis nisl tempor. Suspendisse dictum feugiat nisl ut dapibus.</p>\n<a href=\"#\" class=\"button button-xsmall\">Button</a>"
    block:
      variations: 'box2 disabled'
  custom-2883:
    title: 'Title Outline, Centered Title'
    attributes:
      html: "<div class=\"g-title\">Title Outline, Centered Title</div>\n<p>Phasellus molestie magna non est bibendum non venenatis nisl tempor. Suspendisse dictum feugiat nisl ut dapibus.</p>\n<a href=\"#\" class=\"button button-xsmall\">Button</a>"
    block:
      variations: 'title-outline title-center'
