tinyMCE.addI18n('ru.fullpage_dlg',{
    title: "Свойства документа",
    meta_tab: "Основные",
    appearance_tab: "Вид",
    advanced_tab: "Дополнительно",
    meta_props: "Мета-информация",
    langprops: "Язык и кодировка",
    meta_title: "Заголовок (TITLE)",
    meta_keywords: "Ключевые слова",
    meta_description: "Описание",
    meta_robots: "Robots",
    doctypes: "Тип документа (DOCTYPE)",
    langcode: "Код языка",
    langdir: "Направление текста",
    ltr: "Слева направо",
    rtl: "Справа налево",
    xml_pi: "Объявление XML",
    encoding: "Кодировка символов",
    appearance_bgprops: "Свойства фона",
    appearance_marginprops: "Отступы",
    appearance_linkprops: "Цвет ссылки",
    appearance_textprops: "Свойства текста",
    bgcolor: "Цвет фона",
    bgimage: "Фоновое изображение",
    left_margin: "Левый отступ",
    right_margin: "Правый отступ",
    top_margin: "Верхний отступ",
    bottom_margin: "Нижний отступ",
    text_color: "Цвет текста",
    font_size: "Размер шрифта",
    font_face: "Шрифт",
    link_color: "Цвет ссылки",
    hover_color: "Цвет ссылки при наведении",
    visited_color: "Цвет ссылки после посещения",
    active_color: "Цвет активной ссылки",
    textcolor: "Цвет",
    fontsize: "Размер шрифта",
    fontface: "Семейство шрифтов",
    meta_index_follow: "Индексировать и переходить по ссылкам",
    meta_index_nofollow: "Индексировать и не переходить по ссылкам",
    meta_noindex_follow: "Не индексировать, но переходить по ссылкам",
    meta_noindex_nofollow: "Не индексировать и не переходить по ссылкам",
    appearance_style: "Стиль и свойства стиля",
    stylesheet: "Таблица стилей",
    style: "Стиль",
    author: "Автор",
    copyright: "Копирайт",
    add: "Добавить новый элемент",
    remove: "Удалить выбранный элемент",
    moveup: "Переместить выбранный элемент вверх",
    movedown: "Переместить выбранный элемент вниз",
    head_elements: "Элемент Header",
    info: "Информация",
    add_title: "Элемент Title",
    add_meta: "Элемент Meta",
    add_script: "Элемент Script",
    add_style: "Элемент Style",
    add_link: "Элемент Link",
    add_base: "Элемент Base",
    add_comment: "Комментарий",
    title_element: "Элемент Title",
    script_element: "Элемент Script",
    style_element: "Элемент Style",
    base_element: "Элемент Base",
    link_element: "Элемент Link",
    meta_element: "Элемент Meta",
    comment_element: "Комментарий",
    src: "Src",
    language: "Язык",
    href: "Ссылка",
    target: "Цель",
    type: "Тип",
    charset: "Символы",
    defer: "Отложить",
    media: "Медиа",
    properties: "Параметры",
    name: "Имя",
    value: "Значение",
    content: "Содержание",
    rel: "Rel",
    rev: "Rev",
    hreflang: "Язык ссылки",
    general_props: "Основные",
    advanced_props: "Дополнительно"
});